In [1]:
import numpy as np

In [2]:
arr = np.array([1, 2, 3])
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [3]:
np.ones((2, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [4]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [5]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [6]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [7]:
np.random.rand(3, 2)

array([[0.79176299, 0.40916126],
       [0.58475542, 0.59294078],
       [0.99859536, 0.97125959]])

In [8]:
np.random.randn(3, 2)

array([[-0.02643553,  0.81490752],
       [-0.86331379,  0.17763736],
       [ 1.6338759 , -1.7215823 ]])

In [9]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape)

(2, 3)


In [10]:
print(arr.ndim)

2


In [11]:
print(arr.size)

6


In [12]:
print(arr.dtype)

int64


In [13]:
a = np.array([1, 2, 3])

b = np.array([4, 5, 6])
a + b

array([5, 7, 9])

In [14]:
a * b

array([ 4, 10, 18])

In [15]:
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

In [16]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
np.dot(A, B)

array([[19, 22],
       [43, 50]])

In [17]:
A @ B

array([[19, 22],
       [43, 50]])

In [18]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
np.dot(A, B)
A @ B

array([[19, 22],
       [43, 50]])

In [19]:
arr = np.array([1, 2, 3, 4])
arr.sum()

np.int64(10)

In [20]:
arr.mean()

np.float64(2.5)

In [21]:
arr.max()

np.int64(4)

In [22]:
arr.min()

np.int64(1)

In [23]:
arr.std()

np.float64(1.118033988749895)

In [24]:
arr = np.array([1, 2, 3, 4, 5])
arr[0]

np.int64(1)

In [25]:
arr[1:4]


array([2, 3, 4])

In [26]:

arr[::2]

array([1, 3, 5])

In [27]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr[0, 1]

np.int64(2)

In [28]:
arr[:, 1]


array([2, 5])

In [29]:

arr[1, :2]

array([4, 5])

In [32]:
arr = np.array([1, 2, 3, 4, 5])
mask = arr > 3
arr[mask]

array([4, 5])

In [33]:
arr = np.arange(6)
arr.reshape(2, 3)

array([[0, 1, 2],
       [3, 4, 5]])

In [34]:
a = np.array([1, 2])
b = np.array([3, 4])
np.concatenate((a, b))

array([1, 2, 3, 4])

In [35]:
np.vstack((a, b))
np.hstack((a, b))

array([1, 2, 3, 4])

In [36]:
a = np.array([1, 2, 3])
a + 5 # [6, 7, 8]

array([6, 7, 8])

In [38]:
np.save('array.npy', arr)

In [39]:
loaded_arr = np.load('array.npy')